cursor #e6e0ef
cursor_text_color #c9c3dc

foreground            #e6e0ef
background            #14121c
selection_foreground  #00344f
selection_background  #97ccf8
url_color             #8ecdff

color0   #14121c
color1   #ff729d
color2   #7fff8f
color3   #fff772
color4   #71b9f2
color5   #164b76
color6   #8ecdff
color7   #eff8ff
color8   #99a0a5
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #9ed4ff
color13  #afdcff
color14  #cce8ff
color15  #f8fcff
